apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}-{{ .Values.api.name }}
{{- $labelData := dict "Chart" .Chart "Release" .Release "Name" .Values.api.name }}
spec:
    replicas: {{ .Values.api.replicaCount }} 
    minReadySeconds: {{ .Values.api.minReadySeconds }}
    {{- include "strategy.rolling" . | nindent 4 }}
    selector:
        matchLabels:
            {{- include "labels.noversion" $labelData | nindent 12 }}
    template:
        metadata:
            labels:
                {{- include "labels" $labelData | nindent 16 }}
        spec:
            containers:
            - name: {{ .Release.Name }}-{{ .Values.api.name }}-pod
              image: {{ tpl .Values.api.image . }}
              env:
              - name: DNS
                value: "kube-dns.kube-system"
              - name: X4BAuthPublicKeyUrl
                value: {{ .Values.x4bAuthPublicKeyUrl }}
              - name: LynxApiUrl
                value: {{ .Values.lynxApiUrl }}
              - name: SqlServerUrl
                value: {{ .Values.sqlServerUrl }}
              - name: SqlServerUsername
                value: {{ .Values.sqlServerUsername }}
              - name: SqlServerPassword
                valueFrom:
                  secretKeyRef:
                    name: {{ .Release.Name }}-secret
                    key: sqlServerPassword
              - name: ApiKey
                valueFrom:
                  secretKeyRef:
                    name: {{ .Release.Name }}-secret
                    key: apiKey
              - name: VivWalletUrl
                value : {{ include "vivwallet.url" . }}
              {{- include "resources.large" . | nindent 14 }}
              imagePullPolicy: Always
              ports:
              - containerPort: {{ .Values.api.port }}
            imagePullSecrets:
            - name: {{ .Values.pullSecretName }}