apiVersion: v1
kind: Secret
{{$labelData := dict "Chart" .Chart "Release" .Release "Name" "secret" }}
metadata:
    name: {{ .Release.Name }}-secret
    labels:
        {{- include "labels" $labelData | nindent 8 }}
stringData: 
  sqlServerPassword: {{ .Values.sqlServerPassword | quote }}
  apiKey: {{ .Values.apiKey | quote }}
