apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}-{{ .Values.login.name }}
{{- $labelData := dict "Chart" .Chart "Release" .Release "Name" .Values.login.name }}
spec:
    replicas: {{ .Values.login.replicaCount }} 
    minReadySeconds: {{ .Values.login.minReadySeconds }}
    {{- include "strategy.rolling" . | nindent 4 }}
    selector:
        matchLabels:
            {{- include "labels.noversion" $labelData | nindent 12 }}
    template:
        metadata:
            labels:
                {{- include "labels" $labelData | nindent 16 }}
        spec:
            containers:
            - name: {{ .Release.Name }}-{{ .Values.login.name }}-pod
              image: {{ tpl .Values.login.image . }}
              env:
              - name: AuthenticationEndPoint
                value: "http://{{ .Release.Name }}-{{ .Values.authentication.name }}-svc.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.authentication.port }}"
              - name: DNS
                value: "kube-dns.kube-system"
              {{- include "resources.small" . | nindent 14 }}
              imagePullPolicy: Always
              ports:
              - containerPort: {{ .Values.login.port }}
            imagePullSecrets:
            - name: {{ .Values.global.pullSecretName }}

