apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}-{{ .Values.webapp.name }}
{{- $labelData := dict "Chart" .Chart "Release" .Release "Name" .Values.webapp.name }}
spec:
    replicas: {{ .Values.webapp.replicaCount }} 
    minReadySeconds: {{ .Values.webapp.minReadySeconds }}
    {{- include "strategy.rolling" . | nindent 4 }}
    selector:
        matchLabels:
            {{- include "labels.noversion" $labelData | nindent 12 }}
    template:
        metadata:
            labels:
                {{- include "labels" $labelData | nindent 16 }}
        spec:
            volumes:
              - name: config-volume
                configMap:
                  name: {{ .Release.Name }}-{{ .Values.webapp.name }}-config
            containers:
            - name: {{ .Release.Name }}-{{ .Values.webapp.name }}-pod
              image: {{ tpl .Values.webapp.image . }}
              {{- include "resources.small" . | nindent 14 }}
              imagePullPolicy: Always
              ports:
              - containerPort: 80
              volumeMounts:
                - name: config-volume
                  mountPath: /usr/share/nginx/html/config.js
                  subPath: config.js
            imagePullSecrets:
            - name: {{ .Values.global.pullSecretName }}
