apiVersion: v1
kind: Service
{{$labelData := dict "Chart" .Chart "Release" .Release "Name" .Values.webapp.name }}
metadata:
    name: {{ .Release.Name }}-{{ .Values.webapp.name }}-svc
    labels:
        {{- include "labels" $labelData | nindent 8 }}
spec:
    selector:
        {{- include "labels.noversion" $labelData | nindent 8 }}
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP


