version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-browsers
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Install Chrome latest version
          command: |
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo apt install ./google-chrome-stable_current_amd64.deb
            rm ./google-chrome-stable_current_amd64.deb
      - run:
          command: mvn clean install
          no_output_timeout: 20m
      - store_artifacts:
          path: /home/circleci/.npm/_logs/
