version: 2.1
jobs:
  build-vuejs:
    docker:
      - image: circleci/node:12.13.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Prepare
          working_directory: viv-wallet-app-vue
          command: npm install
      - run:
          name: Lint
          working_directory: viv-wallet-app-vue
          command: npm run lint
      - run:
          name: Build
          working_directory: viv-wallet-app-vue
          command: npm run build
      - run:
          name: Unit Test
          working_directory: viv-wallet-app-vue
          command: npm run test:unit
      - run:
          name: E2E Test
          working_directory: viv-wallet-app-vue
          command: npm run test:e2e

  build:
    docker:
      - image: circleci/openjdk:11-jdk-browsers
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          command: mvn clean install
          no_output_timeout: 20m
      - store_artifacts:
          path: /home/circleci/.npm/_logs/
workflows:
  build_and_test_all:
    jobs:
      - build
      - build-vuejs
