app:
    url: http://localhost:4200
api:
    key: DEV_API_KEY
spring:
    datasource:
        url: jdbc:h2:mem:testdb
    h2:
        console:
            enabled: true
            path: /h2
    flyway:
        enabled: false
x4b:
    auth:
        issuer: X4B
        publicKeyUrl: https://x4b.uat.xcomponent.com/authentication/api/Configurations/Key
lynx:
    vivApiUrl: /api/report/getinfo?name=viv&begin_date=2022-01-01
    userApiUrl: /api/report/getinfoformat?name=report&shortcut=consultants
