app:
  url: http://localhost:4200
api:
  key: DEV_API_KEY
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    enabled: false
x4b:
  auth:
    issuer: X4B
    publicKeyUrl: https://login.uat.xcomponent.com/authentication/api/Configurations/Key
lynx:
  vivApiUrl: TO_BE_DEFINED
  userApiUrl: TO_BE_DEFINED
