app:
  url: http://localhost:4200
spring:
  h2:
    console:
      enabled: true
      path: /h2
x4b:
  auth:
    issuer: X4B
    publicKeyUrl: https://login.uat.xcomponent.com/authentication/api/Configurations/Key
