export enum Role {
    EXPERTISE_MANAGER = "EXPERTISE_MANAGER",
    SENIOR_MANAGER = "SENIOR_MANAGER",
    COMPANY_ADMINISTRATOR = "COMPANY_ADMINISTRATOR",
    CONSULTANT = "CONSULTANT",
}

export const adminOnly = [Role.COMPANY_ADMINISTRATOR];
